apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-site-deployment
  labels:
    app: django-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-site
  template:
    metadata:
      labels:
        app: django-site
      namespace: edu-insane-perlman
    spec:
      containers:
      - name: django-site
        image: leksuss/django-site:latest
        envFrom:
        - secretRef:
            name: secrets
        volumeMounts:
        - name: yandex-root-cert
          mountPath: "/opt/.postgresql"
          readOnly: true
      volumes:
      - name: yandex-root-cert
        secret:
          secretName: yandex-root-cert
          optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: django-site-service
  namespace: edu-insane-perlman
spec:
  selector:
    app: django-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30421
  type: NodePort