apiVersion: v1
kind: Secret
metadata:
  name: django-site-secrets
type: Opaque
stringData:
  SECRET_KEY: 'generated-secret-key'
  DEBUG: !!Bool True
  DATABASE_URL: 'postgres://DB_LOGIN:DB_PASSWORD@DB_HOST:DB_PORT/DB_NAME?sslmode=verify-full&/opt/.postgresql/root.crt'
  ALLOWED_HOSTS: '127.0.0.1,localhost,edu-insane-perlman.sirius-k8s.dvmn.org'