apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  SECRET_KEY: '46gxlb_xvm+4jtt0(u(npn_r#ksv8-kpjkh6yopcc4v(*&b@35'
  DEBUG: !!Bool True
  DATABASE_URL: 'postgres://edu-insane-perlman:@11WPSNdM3wvH_e@@rc1b-j03a218khoxjlwdi.mdb.yandexcloud.net:6432/edu-insane-perlman?sslmode=verify-full&sslrootcert=/opt/.postgresql/root.crt'
  ALLOWED_HOSTS: '127.0.0.1,localhost,edu-insane-perlman.sirius-k8s.dvmn.org'