apiVersion: v1
kind: Service
metadata:
  name: edu-insane-perlman-django
  namespace: edu-insane-perlman
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30421
  type: NodePort