apiVersion: v1
kind: Service
metadata:
  name: django-site-service
  namespace: edu-insane-perlman
spec:
  selector:
    app: django-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30421
  type: NodePort