apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: '@monthly'
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 31536000  # year in seconds
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: myapp:latest
            imagePullPolicy: Never
            envFrom:
              - configMapRef:
                  name: env-vars
              - secretRef:
                  name: env-secrets
            command: ['python', 'manage.py', 'clearsessions']
          restartPolicy: Never
      backoffLimit: 3